services:
  qpid:
    image: apache/qpid-broker-j:latest
    environment:
      QPID_ADMIN_USER: guest
      QPID_ADMIN_PASSWORD: guest
    ports:
      - "56720:5672"
      - "58080:8080"

  artemis:
    image: apache/artemis:latest-alpine
    environment:
      ARTEMIS_USER: guest
      ARTEMIS_PASSWORD: guest
      ANONYMOUS_LOGIN: "false"
    ports:
      - "56730:5672"
      - "58161:8161"

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "56740:5672"
      - "58172:15672"

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    ports:
      - "58474:8474"
